#global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout:     1m
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'metrics'
    scrape_interval: 15s

    static_configs:
      - targets: ['docker.for.mac.host.internal:9990']

  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
